use_frameworks!

platform :ios, '12.1'

target 'IdentifyIOS_Example' do
  pod 'IdentifyIOS', :path => '../'
  
  pod 'QKMRZParser'
  pod 'CHIOTPField/Two'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftSignatureView'
  pod 'GoogleMLKit/FaceDetection'
  pod 'WeScan', '>= 0.9'
  pod 'GoogleMLKit/FaceDetection'
  pod 'GoogleMLKit/TextRecognition'
  pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios'
  target 'IdentifyIOS_Tests' do
    inherit! :search_paths

    
  end
end
